# Generated by Django 3.2.9 on 2021-11-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('linkpost', models.CharField(max_length=255)),
                ('post', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
                ('device', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Minute', models.DateField(max_length=10)),
                ('Hour', models.DateField(max_length=10)),
                ('Day_of_month', models.DateField(max_length=10)),
                ('Month', models.DateField(max_length=10)),
                ('Day_of_week', models.DateField(max_length=10)),
            ],
        ),
    ]
