# Generated by Django 3.2.9 on 2021-11-09 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='linkpost',
            new_name='Link_post',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='Names',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='id',
            new_name='_id',
        ),
    ]
